githubuser: pitchopp
githubpassword: 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
app_name: gpt-assistant
home: "/home/{{ app_user }}"
app_folder: "{{ home }}/{{ app_name }}"
git_repo_url: https://{{ githubuser }}:{{ githubpassword }}@github.com/pitchopp/gpt-assistant.git
# gunicorn_workers: 4
gunicorn_log_level: debug