---
- name: Create group {{ username }}
  group:
    name: '{{ username }}'

- name: Create user {{ username }}
  user:
    name: "{{ username }}"
    state: present
    groups: sudo
    shell: /bin/bash
    append: true
    create_home: true
    home: "{{ home }}"

- name: Setup passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

# - name: make user sudoer
#   shell: 
#     cmd: echo "{{username}} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/{{username}}
#   become: true

- name: create .ssh folder
  file:
    path: "{{home}}/.ssh"
    state: directory
    owner: "{{username}}"
    group: "{{username}}"

- name: Copy authorized keys
  copy:
    remote_src: true
    src: /root/.ssh/authorized_keys
    dest: "{{home}}/.ssh/authorized_keys"
  become: true

# - name: Disable password authentication for root
#   lineinfile:
#     path: /etc/ssh/sshd_config
#     state: present
#     regexp: '^#?PermitRootLogin'
#     line: 'PermitRootLogin prohibit-password'
