- name: Install Nginx web server
  become: true
  apt:
    name: nginx
    state: present

- name: Start and enable Nginx service
  become: true
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: ufw allow Nginx Full
  ufw:
    rule: allow
    name: Nginx Full

- name: reload ufw
  ufw:
    state: reloaded