---
- name: Create user group
  group:
    name: '{{ username }}'

- name: Create user
  user:
    name: "{{ username }}"
    home: "{{ home }}"
    shell: /bin/bash
    groups: sudo
    append: yes

- name: make user sudoer
  shell: 
    cmd: echo "{{username}} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/{{username}}
  become: true

- name: Create home directory
  file:
    path: "{{ home }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: create .ssh folder
  file:
    path: "{{home}}/.ssh"
    state: directory
    owner: "{{username}}"
    group: "{{username}}"

- name: copy authorized keys
  copy:
    remote_src: true
    src: /root/.ssh/authorized_keys
    dest: "{{home}}/.ssh/authorized_keys"
  become: true