---
- name: Create user ocmentorassistant
  hosts: vpsperso
  become: true
  roles:
    - create-user
  tags:
    - init
    - create-user
  vars:
    - username: mentoroc

- name: Deploy Mentoroc Frontend React app
  hosts: vpsperso
  roles:
    - role: docker
      tags:
        - init
        - docker
    - role: mentoroc-webapp
    - role: certbot
      tags:
        - init
        - certbot
  vars_files:
    - ../../secrets.yml
  vars:
    - app_user: mentoroc
    - server_domain: mentoroc.com
    - certbot_email: contact@mentoroc.com
    - certbot_domain: "{{ server_domain }}"
