---
- name: Create user ocmentorassistant
  hosts: vpsperso
  become: true
  roles:
    - create-user
  tags:
    - init
    - create-user
  vars:
    - username: ocmentorassistant

- name: Setup pyenv
  hosts: vpsperso
  roles:
    - staticdev.pyenv
  tags:
    - init
    - python
  vars:
    - pyenv_python_versions:
      - 3.10.6
    - pyenv_global:
      - 3.10.6
    - pyenv_env: system

- name: Setup nginx
  hosts: vpsperso
  roles:
    - nginx
  tags:
    - init
    - nginx

- name: "Deploy OC Mentor Assistant app"
  hosts: vpsperso
  roles:
    - role: postgresql
      tags:
        - init
        - postgresql
    - role: poetry
      tags:
        - init
        - python
    - role: oc-mentor-assistant
      tags:
        - app
    - role: certbot
      tags:
        - init
        - certbot
  vars_files:
    - ../../secrets.yml
  tags:
    - oc-mentor-assistant
  vars:
    - app_user: ocmentorassistant
    - create_db: true
    - db_name: "{{ app_user }}"
    - db_user: "{{ app_user }}"
    - db_password: "{{ OCMENTORASSISTANT_DB_PASSWORD }}"
    - poetry_home: "/home/{{app_user}}/.local"
    - poetry_path: "{{ poetry_home }}/bin/poetry"
    - server_domain: mentor.chella.tech
    - certbot_email: contact@chella.tech
    - certbot_domain: "{{ server_domain }}"

# - name: install elk
#   hosts: vpsperso
#   roles:
#     - elk
#   tags:
#     - init
#     - elk
#   vars_files:
#     - ../../secrets.yml
#   vars:
#     - kibana_domain: kibana.chella.tech
#     - certbot_email: contact@chella.tech
#     - certbot_domain: "{{ kibana_domain }}"