---
- name: Setup a basic firewall with ufw
  hosts: vpsperso
  roles:
    - firewall

- name: Create user groot
  hosts: vpsperso
  roles:
    - create-user
  vars:
    - username: groot

- name: "Install packages and configure server"
  hosts: vpsperso
  become: true
  roles:
    - ssh
    - tools

- name: Add encrypted SSH key to authorized_keys
  hosts: vpsperso
  become: true
  tasks:
    - name: Add SSH key to authorized_keys
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "../ssh_keys/*"
